<?php
$ABS = array( // Ajax Browser Sentences
'language_in_English' => 'German',
'language_in_Language' => 'Deutch',
'language_abbreviation' => 'de',
'language_translator' => 'none',
'language_version' => '0.0.1',
'language_src_flag' => 'src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAGzSURBVHjaYvTxcWb4+53h3z8GZpZff/79+v3n/7/fDAz/GHAAgABi+f37e3FxOZD1Dwz+/v3z9y+E/AMFv3//+Qumfv9et241QACxMDExAVWfOHkJJAEW/gUEP0EQDn78+AHE/gFOQJUAAcQiy8Ag8O+fLFj1n1+/QDp+/gQioK7fP378+vkDqOH39x9A/RJ/gE5lAAhAYhzcAACCQBDkgRXRjP034R0IaDTZTFZn0DItot37S94KLOINerEcI7aKHAHE8v/3r/9//zIA1f36/R+o4tevf1ANYNVA9P07RD9IJQMDQACxADHD3z8Ig4GMHz+AqqHagKp//fwLVA0U//v7LwMDQACx/LZiYFD7/5/53/+///79BqK/EMZ/UPACSYa/v/8DyX9A0oTxx2EGgABi+a/H8F/m339BoCoQ+g8kgRaCQvgPJJiBYmAuw39hxn+uDAABxMLwi+E/0PusRkwMvxhBGoDkH4b/v/+D2EDyz///QB1/QLb8+sP0lQEggFh+vGXYM2/SP6A2Zoaf30Ex/J+PgekHwz9gQDAz/P0FYrAyMfz7wcDAzPDtFwNAgAEAd3SIyRitX1gAAAAASUVORK5CYII="',

0 => '?',// 'Gestionnaire de fichier via http',
1 => '?',// 'Ouverture d\'une session AJAX-Browser',
2 => '?',// 'Mode',
3 => '?',// 'Last loged',
4 => '?',// 'Cancel',
5 => '?',// 'Login',
6 => '?',// 'Password',
7 => '?',// 'Sign Out',
8 => '?',// 'Documentation',
9 => '?',// 'visit',
10 => '?',// 'OK',
11 => '?',// 'UserName',
12 => '?',// 'arborescence',
13 => '?',// 'gallerie',
14 => '?',// 'recomandé',

15 => '?',// 'New',
16 => '?',// 'Couper',
17 => '?',// 'Copier',
18 => '?',// 'Coller',
19 => '?',// 'Rename',
20 => '?',// 'MultiRename',
21 => '?',// 'Erase',
22 => '?',// 'Download',
23 => '?',// 'This Only',
24 => '?',// 'Upload',
25 => '?',// 'Open / Edit',
26 => '?',// 'Proprietés',
27 => '?',// 'Deplacer ici ',
28 => '?',// 'Copier ici ',
29 => '?',// 'Please Wait, Loading...',
30 => '?',// 'Repport Bug or/and Suggest',
31 => 'Taille',
32 => 'Type',
33 => 'Date',
34 => 'Droits',
35 => '',// ' trying, You are Blacklisted !',

// fichier ManageSuperGlobales.php
100 => '?',// 'Impossible de créer le fichier "AJAX-Array.var" dans ".AJAX-B" veuillez verifier les droits',
101 => '?',// 'Aucun fichier de configuration n\'as été trouvé',
102 => '?',// 'Veuillez definir un compte Administrateur :',

// fichier InitHTML.php
200 => '?',// 'Domaine vue sous AJAX-Browser',
201 => '?',// 'Nouveau dossier ou fichier',
202 => '?',// 'Renomer cet element, la selaction ou les contenus...',
203 => '?',// 'Supprimer toute la selection',
204 => '?',// 'Forcer le Telechargement',
205 => '?',// 'Telechargement de la selection au format ',
206 => '?',// 'Depposer des fichiers vers ce repertoire.',
207 => '?',// 'Contacter l\'administrateur du Browser',
208 => '?',// 'Filtre le contenu visible selon le masque.',
209 => '?',// 'Extraire le lien vers ce dossier',
210 => '?',// 'Configurer AJAX-Browser',
211 => '?',// 'Gestion des comptes Utilisateurs',
212 => '?',// 'Gestion de mon profil Utilisateur',
213 => '?',// 'A Propos de AJAX-Browser',
214 => '?',// 'Gestion des comptes',

// fichier ExplorerTools.php
// fichier ArchiveTools.php

// fichier SessionTools.php
300 => '?',// 'Impossible d\'accéder et de créer le repertoire de SESSIONS',
301 => '?',// 'Site officiel d\'AJAX-Browser',

// fichier Command.php
401 => '?',// ' has been created with default setting.',
402 => '?',// 'Pas de nounelle version !',
403 => '?',// 'Miroir injoignable !',

// fichier Setting.php
500 => '?',// 'Double Click pour choisir le dossier ouvert',
501 => '?',// 'AJAX-Browser Version',
502 => '?',// 'E-mail de(s) l\'Administrateur(s).',
503 => '?',// 'Separer par des virgules.',
504 => '?',// 'Serveur de mise a jour.',
505 => '?',// 'Vide => '?',// pas de mise a jour !',
506 => '?',// 'Sorry Miror unreachable :-(',
507 => '?',// 'No Update Avaible, you have the last version installed ;-)',
508 => '?',// 'Update Avaible',
509 => '?',// 'Fichier consideré comme trés peut sensible',
510 => '?',// 'Fichier consideré comme sencible',
511 => '?',// 'Fichier ouvrable en ligne avec CodePress',
512 => '?',// 'Dossier pour les fichiers espions',
513 => '?',// 'Enregistrement des fichiers.SPY',
514 => '?',// 'Les IP.',
515 => '?',// 'Les LOG.',
516 => '?',// 'Les action.',
517 => '?',// 'Les dossiers parcourus',
518 => '?',// 'A utiliser avec moderation (lourd)',
519 => '?',// 'Voir la legislation en vigueur',
520 => '?',// 'Dossier pour les miniatures',
521 => '?',// 'Intervale de chargement des miniatures',
522 => '?',// 'Network 100Mb/sec, 6000 img/min.',
523 => '?',// 'Bon serveur et bonne connexion, 600 img/min.',
524 => '?',// 'Serveur, connexion et images normaux, 240 img/min (recomande)',
525 => '?',// 'Serveur lent ou grosse image, 120 img/min.',
526 => '?',// 'Serveur trés lent ou image enorme, 40 img/min.',
527 => '?',// 'Effacer les anciennes miniature.',
528 => 'BlackListe.',

// fichier Account.php
600 => '?',// '',
601 => '?',// 'Modifier ce compte',
602 => '?',// 'Supprimer ce compte',
603 => '?',// 'Ajouter un Utilisateur',
604 => '?',// 'E-mail de l\'utilisateur.',
605 => '?',// 'Changer ce code',
606 => '?',// 'Spécifier un nouveau code',
607 => '?',// 'Choose New PassWord !',
608 => '?',// 'No PassWord Change !',
609 => '?',// 'Vous pouvez le changer en cochant la case de drote',
610 => '?',// 'Configuration d\'accé.',
611 => '?',// 'Dossier par defaut a l\'ouverture',
612 => '?',// 'Parcourir les dossiers parents !',
613 => '?',// 'Mode d\'affichage par defaut',
614 => '?',// 'Taille des miniatures en mode gallerie',
615 => '?',// 'Minuscule',
616 => '?',// 'Moyenne',
617 => '?',// 'Grande',
618 => '?',// 'Enorme',
619 => '?',// 'Gigantesque',
620 => '?',// 'Droits sur le domaine.',
621 => '?',// 'Creer des elements',
622 => '?',// 'Sera autorise a créer des fichiers ou des dossiers',
623 => '?',// 'Renomer les elements',
624 => '?',// 'Sera autorisé a renimer les fichiers et dossiers',
625 => '?',// 'Suprimer des elements',
626 => '?',// 'Sera autorisé a suppr',
627 => '?',// 'Voir les elements cachés',
628 => '?',// 'Sera autorisé a voir les fichiers cachers (commancant par un \'.\')',
629 => '?',// 'Copier des elements',
630 => '?',// 'Sera autorisé a Copier des elements',
631 => '?',// 'Deplacer des elements',
632 => '?',// 'Sera autorisé a Deplacer des elements',
633 => '?',// 'Utilisation de CodePress.',
634 => '?',// 'Visu CodePress',
635 => '?',// 'Edition CodePress',
636 => '?',// 'Ceci est valable pour les masques definis par l\'ADMIN :',
637 => '?',// 'Transfert de données.',
638 => '?',// 'Peut Télécharger tous se qui lui est accéssible !',
639 => '?',// 'Upload de fichier par AJAX-Browser',
640 => '?',// 'Aucun (meme pas d\'images...)',
641 => '?',// 'Seulement les fichiers',
642 => '?',// 'Tous sauf',
643 => '?',// 'Tous, sans aucune restriction (admin)!',
644 => '?',// 'Config Globale d\'administration.',
645 => '?',// 'Configuration generale d\'AJAX-Browser',
646 => '?',// 'Configuration de tous les comptes utilisateur',
647 => '?',// 'Detail des connection',
648 => '?',// 'Obtenir d\'autres langue',
649 => '?',// 'Demander d\'autres langue a l\'admin',
650 => '?',// 'Décompresser des éléments',
651 => '?',// 'Sera autorisé à Decompresser les elements ZIP, TAR, GZIP, BZIP2',
652 => '?',// 'Remove to BlackListe',

// fichier ArborescenceAddon.php
// fichier Arborescence.php
// fichier GallerieAddon.php
// fichier Gallerie.php
'getFF' => '?',// 'Télécharger Mozila Firefox, afin de profiter pleinement de AJAX-Browser',

// fichier Contact.php
701 => '?',// 'Votre message a ete envoyee:',
702 => '?',// 'Un probleme s\'est produit lors de l\'envoi du message.',
703 => '?',// 'Ressayez...',
704 => '?',// 'Votre adresse e-mail (obligatoire)',
705 => '?',// 'Titre de message (obligatoire):',
706 => '?',// 'Message (obligatoire):',

// fichier ManageUpload.php
801 => '?',
802 => '?',
803 => '?',
804 => '?',
805 => '?',

// fichiers *.JS
900 => '?',
906 => '?',
907 => '?',
908 => '?',
909 => '?',
910 => '?',
911 => '?',
912 => '?',
913 => '?',
914 => '?',
915 => '?',
916 => '?',
917 => '?',
918 => '?',
919 => '?',
);
?>