# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 13 Oct 2009 14:44:04 +0200
*               @ALL          1
*               @user         8
